### ISSUE TITLE
NO_LIGHT

### ISSUE THREAD

**Issue by thanos-k** [fluffos/fluffos#275]
I had not updated our driver for some time and just now found out that no_light is permantly defined now.
since we do rely quite heavily on add_light is there a chance for that change to be reversed or there is no chance of that for some valid reason ?

**Comment by thefallentree** [comment]
my understanding is that add_light can be pretty easily implemented using simul_efun. Will you be willing to try to do that?

**Comment by thanos-k** [comment]
Pretty easily is not the way I would put it and having a simul_efun has its own problems.

To be frank it would be easier for me to fork fluffOS and maintain a separate tree even if the constant formatting changes make applying diffs complicated.

I understand that a lot of muds do not use it but removing functionality that has been around for decades that caused minimal problems is a mistake. 
FluffOS is not supposed to be the custom driver for a few muds but a lot more general. So unless code does not cause problems and has a minimal maintenance footprint I would have expected it to remain in place. 

but just my 2cents.

**Comment by thefallentree** [comment]
> Pretty easily is not the way I would put it and having a simul_efun has its own problems.

Judging from the code, LIGHT is simply maintained by having a "total_light" number for each object, add/substract on move.  Which should be relatively easy to be implemented in simul_efun. Can you elaborate on the "own set of problem" part?

For this feature, yes it is pretty small, and I've reverted changes like this before . I can add this back. A better way maybe to implement this as a PACKAGE, as we are not getting away with that anyway.

But I want to be clear that the goal here is sure not to make FluffOS a custom driver, As long as external feedback like this continue to flow in.  To be frank, as a lone maintainer, I have no choice but to catering my most vocal customers.

Each compile time option adds some weight to the driver codebase, in order to move forward (my goal is to make LPC runtime embeddable like LUA), some calculated risk need to be taken.

FluffOS has been heavily refactored from 3.0-alpha-7.4 to 3.0-alpha-9.0 , so some incompatibility should not be surprising.

**Comment by thanos-k** [comment]
I can go through the code to see what is going on in there.
My problem is that our mudlib is quite old (25years and counting) and during that time many people did "clever" hacks all over the place. 
I can go through the code all over and see where it causes troubles and so on but it will take me a couple of days to get back to you. 
We have something called nightvision as an ability for certain guilds and I remember that was implemented using set_light overrides and hacks all over the place.
I suppose it is a chance to clean up code but it will require some heavy testing. 
Will get back to you but if the goal is to make it as lean as possible I understand that you might want to remove features that are not universally used. 
Consider it closed. worst case scenario I keep a different clone of FluffOS and work with that.

**Comment by thanos-k** [comment]
This is a bit unrelated but consider running a poll about the local_options file people are using and how it deviates from the default local_options.README so you know what features are being used and know what to expect :)
Thanks for all the great work.

**Comment by thefallentree** [comment]
@thanos-k NO_LIGHT has been added back, please let me know if it works fine.   Removing your lib from this dependency is however still preferred.
