### ISSUE TITLE
<bug>(packages/core/efuns_main.cc): generate_source ?

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#287]
While looking through the config files I found indirect references to an efun 'generate_source'…
I haven't followed the whole build process, so this _might_ be a non issue!
But nowhere in the source I found the actual function 'generate_source' used by the efun, neither could I find any references to 'master::valid_compile_to_c()' apart from it's documentation file…

**Comment by quixadhal** [comment]
Once upon a time, MudOS used to have a compile_to_C feature, but it was
broken decades ago and never fixed because nobody really ever used it.

Generally speaking, if something is used enough to need a speedup from
being in the driver, you likely want to hand code it in C to get the
biggest benefit.

I would suggest removing all remaining references and documentation, as
it's doubtful such a feature would ever return.  If you really wanted that
kind of functionality, writing a standalone LPC -> C translator would be
easier.

**Comment by Shea690901** [comment]
Not today anymore, but i'll look through the code/documentation for this…

**Comment by thefallentree** [comment]
yeah, compile_to_c seems totally dead now, we should get rid of all those junk
