### ISSUE TITLE
package/mudlib_stats: backbone_uid/backbone_domain

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#296]
In vm/internal/master.cc line 142 there is a call to set_backbone_domain with the return value of master::get_bb_uid() as argument.
What if I want to differentiate between backbone user and backbone domain???

**Comment by thefallentree** [comment]
well, first of all, I will admit i don't really understand this whole uid thing (chinese lpmud doesn't use it much)  care to explain what is a user/domain and this backbone thing really fast?

**Comment by Shea690901** [comment]
That's on one side part of the (e)uid system with efuns/master applies
 - get_uid
 - set_euid/get_euid
 - get_root_uid/get_bb_uid
 - creator_file
 - valid_*

And on the other hand the statistics part with efuns/master applies
 - author_stats/domain_stats
 - author_file/domain_file

Domains can be seen either as user groups (security side) or as mud areas (statistics side).
Root, like with unix, is the uid with the most privileges and backbone could be seen as nobody, who has no privileges by itself, but is what every one needs (standard objects like torch, sword, chainmail, …) and belongs to no single user/group.

And now the driver code is forcing me to use a **user id** (master::get_bb_uid) to use as the **area** (driver::set_backbone_domain) which will get the statistics for the master (and other objects?)!
Since it's part of the statistics system it should on one hand use master::domain_file instead; on the otherhand, since it's want's to explicitly set the **backbone**domain either a new apply would be needed or domain_file would need a special argument (probably "") to know it should return explicitly the backbone domain.

**Comment by quixadhal** [comment]
Classic mudlibs used uid as a means to uniquely identify a user (or NPC),
and that information was commonly used both for security functions and for
object ownership.  Taken to an extreme, if I attacked you with a poisoned
dagger, the lingering poison effect would be "owned" by me, and thus have
my uid.

euid, like in unix, was for permissions.  If you were holding a wizard's
tool (such as the old paintbrush), your euid would be that of the tool,
allowing you to edit room descriptions which your own uid didn't have
permission to do directly.

the domain functions were used on larger muds to ensure that creators who
were assigned to various areas were actually producing content as
requested.  If you also kept usage data, you could further use it to see
what areas were popular and thus decide if they needed to be tweaked.

backbone can also be thought of as the catch-all for domains.  If you ask
for statistics about an object from the system areas, it would be part of
the backbone set, since it belongs to neither a single domain nor a
wizard's area.

In many ways, I kindof think ALL of these things should be lumped together
into a single package (if they aren't already), since most mudlibs either
tend to need ALL of them, or do them all in LPC anyways.

**Comment by Shea690901** [comment]
They are in two packages:
- packages/uids
- packages/mudlib_stats

It's surly not wrong to combine both (for the stated reason), but I think more important would be the strict distinction between user and group…
Perhaps even the addition of ```efun::set_egid```/```efun::get_egid```…
With the combination of both packages this would give:

function | 'package' | apply | efun | returns
---- | ---- |---- | ---- | ----
author_file | both | x | | userid for new object (string)
domain_file | both | x | | groupid for new object (string)
(get_root_uid | security | x | | privileged user (string))
get_bb_uid | security | x | | unprivileged user (string)
get_bb_gid | statistics/(both?) | x | | unprivileged group (string)
set_euid | security | | x | (not) allowed (boolean)
set_egid | security | | x | (not) allowed (boolean)
get_euid | security | | x | effective userid (string)
get_egid | security | | x | effective groupid (string)
author_stats | statistics | | x | user statistics (mapping)
domain_stats | statistics | | x | group statistics (mapping)

```master::creator_file(string)``` wouldn't be needed any more and I'm not sure about get_root_uid…
I think instead of ```master::get_root_uid()``` one could use ```master::author_file(__MASTER_FILE__)```…
And the management of  a privileged group could be handled completely within the mudlib, I don't think it would be necessary to store it somewhere inside the driver, even the bb_uid/bb_gid would only be needed if they are automatically trusted…

**Comment by thefallentree** [comment]
this is done, right?
