### ISSUE TITLE
Weird crash. Any ideas ?

### ISSUE THREAD

**Issue by thanos-k** [fluffos/fluffos#357]
This is a weird crash that has happened a few times while snooping but definately not all the time .
I have attached the backtrace as bt.txt and the relevant part of the code is in snoop.txt 
(crashes at the map_array part)

[snoop.txt](https://github.com/fluffos/fluffos/files/888368/snoop.txt)
[bt.txt](https://github.com/fluffos/fluffos/files/888365/bt.txt)

**Comment by thefallentree** [comment]
This definitely seems like a memory corruption bug. Have you tried running under valgrind?

**Comment by thanos-k** [comment]
I find it very hard to actually reproduce in our test environment and it is wildly unpredictable.
running the whole live mud under valgrid and "playing with fire" hoping for a crash is not something
I would like doing.

But I think I narrowed it down a bit further
Apr 24 15:18:39 JVGH001 driver[9498]: Error in error handler: *Bad argument 1 to mapp()
Apr 24 15:18:39 JVGH001 driver[9498]: Expected: int or string or array or object or mapping or function or float or buffer or class Got: T_INVALID.
If that helps at all ....

**Comment by thefallentree** [comment]
Ok, so it maybe a use after free?

**Comment by thanos-k** [comment]
Sorry but did not quite understand what you mean.

**Comment by Shea690901** [comment]
He means it´s a bad idea to use an allocated object after it has been deallocated (after free)...
Apparently that´s what happening in your case:
the error handler want´s to `mapp` some object but what ever object it got as argument is already freed:
`Expected: int or string or array or object or mapping or function or float or buffer or class Got: T_INVALID`

**Comment by thanos-k** [comment]
The problem starts a bit before than the mapp function.
Check the very first post the backtrace :  
(fmt=0x7ff3b3fbd4d0 "Bad type argument to +.  Had %s and %s.\n") at vm/internal/simulate.cc:1946
        err_buf = "*Bad type argument to +.  Had string and *invalid*.\

so not sure where something was freed ...

**Comment by Shea690901** [comment]
Of course the error resides before the `mapp`, otherwise it wouldn´t get a freed object as argument...
And
> (fmt=0x7ff3b3fbd4d0 "Bad type argument to +. Had %s and %s.\n") at vm/internal/simulate.cc:1946
> err_buf = "*Bad type argument to +. Had string and **_invalid_**.\

even show´s the problem...
Rewrite your error handler:
 check for the type of the variables and depending on it´s result (_**which might be T_INVALID**_) produce your output
With a little luck it helps with finding the original error....

Hmmm.... T_INVALID? Doesn´t really sound as if it´s freed....
btw.:
```
if (stringp(cl) && !str) {
      msg = (string)cl;
   }
   else {
      msg = str;
   }
```

is it possible that `cl` doesn´t contains a string and **_at the same time_** `!str` is true?
You also might want to check the type of `snoop_line`...

Perhaps the `explode` get´s wrong arguments....

**Comment by quixadhal** [comment]
I don’t know the internals of fluffos, so pardon my assumptions…

But, to me as a programmer, it seems like the only way any LPC object could become T_INVALID would be if it were never initialized at all, or if it were freed but never removed from the system storage pool.  AFAIK, all LPC variables are initialized with integer 0 values, regardless of type (type sticks to values, not variables).  So, if you declare a mapping, it will initially be 0.  Once you use the mapping properly (set it to be ([ ])), it gets the proper type and value.  Since there is an undefinedp(), I have to assume it checks the type and that it’s either T_INVALID, or there’s a specific T_UNDEF or something.

I imagine fluffos uses reference counting and does some kind of garbage collection, so variables and objects which become unreferenced get moved to a list of things to be freed, and at some point might actually be either freed or recycled.

Soooo, if you have a T_INVALID, either it’s a bug in the reference tracking somewhere, and some variable got marked as ready-to-free when it still had a reference…. Or a bug in the recycling/allocation code that didn’t reset the type when moving it back into circulation.

That’s my uninformed guess. 😊

Sent from Mail for Windows 10

**Comment by thanos-k** [comment]
I finally managed to track down the problem and it has to do with send_nullbyte which we use in our mudlib to create a sort of keepalive for problematic connections.

Now unfortunately the nullbyte is not detected at all thus creating the problem.
So even assuming I changed the code in receive snoop as follows 

`nomask void receive_snoop(string msg) {
    if(!msg) return; //passes
    if(undefinedp(msg)) return; //passes
    if(nullp(msg)) return; //passes
    if (typeof(msg) == 0) return; //this also fails creating errors
.....
}`

this will cause errors and when I try to check what kind the error is in the error_daemon, that creates more errors resulting in a crash.
unfortunately there is no invalidp efun to fix this.
the only way around it was to check using if(identify(msg) == "\"\"").

The other and probably the correct solution is to patch the driver to send the proper telnet nullbyte
of "\0" instead of just "", but I remember that causes some old telnet clients to actually show a 0(which is obviously incorrect)

Lastly I attach the valgrind reports of the crash for your inspection since the driver should not crash in any case. 


[valgrind.txt](https://github.com/fluffos/fluffos/files/1065833/valgrind.txt)

**Comment by thefallentree** [comment]
661692c3b61f274d09fe88fadefbe0ea0799dc02 should be fixing this issue

**Comment by thefallentree** [comment]
please try new version and reopen if the issue still here.

**Comment by quixadhal** [comment]
Just to clarify, the TELNET protocol actually expects raw NUL bytes to be escaped as the sequence IAC NUL.
If you really meant just sending a NUL out of a TCP socket, sending NUL by itself is just fine.  But they’re not
the same thing. 😊

Sent from Mail for Windows 10
