### ISSUE TITLE
Do not only support bash

### ISSUE THREAD

**Issue by lpapp** [fluffos/fluffos#358]
build.FluffOS's current shebang is #!/bin/bash. I would like to be able to use with different type of shells.

**Comment by thefallentree** [comment]
well, I'm not sure why?

**Comment by lpapp** [comment]
Unfortunately, not everyone uses bash.

**Comment by Shea690901** [comment]
Standard would be
`#!/bin/sh`
Even if it´s not bash, then it might be zsh, ksh or even a real bourn shell, but regardless of the actual shell behind this path:
it can be found and responds to a common subset of keywords...
Of course, when switching to `/bin/sh`, some construct´s can´t be used any more without introducing some incompatibilities ;)

**Comment by quixadhal** [comment]
The vast majority of things I do with shell scripts use bash, and I’d feel crippled if I had to not use features to make it work with plain old /bin/sh.  I can’t think of a platform where bash isn’t available, so even if you don’t use it for your login shell, you should be able to install it for use in the build process.

You can make the same argument for makefiles too.  Don’t allow GNUmakefile because not everyone uses GNU make, and force yourself to use the crufty old version of make from 1970.

Considering that FluffOS is already planning to use the Go language, which is *NOT* widely adopted, I hardly think a quibble over bash vs sh warrants any change to workflow.

Sent from Mail for Windows 10

**Comment by Shea690901** [comment]
I don´t remember if it was AIX or IRIX, but one of them had ksh as standard, all other unices should have bash installed (at least afaik)...

**Comment by thefallentree** [comment]
My argument is, the goal for fluffos project is not to run on as many
platform as possible. At least not on current stage.

Some of you may disagree, but I would rather redirect your helpful engery
toward code cleanup and features on the supported platform instead of
arguing about it.

Cheets.
