### ISSUE TITLE
Move to more C++ style code?

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#379]
I am not sure if this is a good idea but it might make it easier to incorporate the testing frameworks and also make the code more modular. The idea is to slowly migrate some of the interfaces to a more C++ style. Alot of the code is currently a bit less tidy than it could be because there are a lot of branches which could be replaced with dynamic dispatch or hidden inside methods placed inside a datatype.

**Comment by thefallentree** [comment]
It's hard to judge what is better until some concert change.  My golden rule in this area is less code = better.  If you have something to send a PR it is always welcome. 

Since this doesn't really seems to be a "issue", until there are some concrete actionable , I'm closing. But we can always chat offline
