### ISSUE TITLE
new otable.cc code review needed before I try incorporating it.

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#384]
I decided to revisit adding a new otable singleton object as a place holder for the old otable code. This is slightly updated but since I am a beginner at C++11 style code I had a few questions about incorporating the test frameworks and so on.

The code is "weakly" dependent on object_t since it just keeps the pointer in a location where it can be retrieved. The problem I am having is how best to break this dependency for testing purposes if possible and supply any old object_t named object to replace it. Is it best to do as follows-

class object_t; //forward declaration.

some #define to include the alternate definitions of object_t. and test with different variations.  Here is the current code-
```
`#include<cassert>
#include<list>
#include<memory>
#include<string>
#include<unordered_map>

struct object
{
    std::string name;
};

class ObjectTable final
{
public:
    using K = std::string;
    using V = object*;
    using L = std::list<V>;
    using M1 = std::unordered_map<K,V>;
    using M2 = std::unordered_map<K,L>;
    using S = std::shared_ptr<ObjectTable>;

    static S get();
    bool insert(K k, V v);
    V find(K const & k);
    L children(K const & k);
    bool remove(K const & k);
private:
    static S instance_;

    ObjectTable();
    K basename(K k);
    
    M1 objects_;
    M2 children_;

};

ObjectTable::S ObjectTable::instance_ = nullptr;

ObjectTable::ObjectTable()
:objects_({}),children_({})
{}

//refactor this method into it's own public class for testing purposes?
ObjectTable::K ObjectTable::basename(ObjectTable::K k) {
    auto i = k.begin();
    for(; *i == '/' ;++i)
    k.erase(k.begin(),i);
    
    auto j = k.find('#');
    if(j != std::string::npos )
        k.erase( k.begin() + j, k.end() );
    i = k.end() - 1;
    for(;i-1 != k.begin() && *i == 'c' && *(i-1) == '.';i -= 2);
    k.erase(i, k.end() );
    return k;
}

ObjectTable::S ObjectTable::get() {
    if( instance_ == nullptr )
        instance_ = S( new ObjectTable() );
    return instance_;
}

bool ObjectTable::insert(ObjectTable::K k,V v) {
    auto i = objects_.find(k);
    if( i == objects_.end() ) {
        objects_.insert( std::make_pair(k,v) );
        children_.insert( std::pair<K, L>( basename(k), {v} ) );
        return true;
    } 
    else {
        return false;
    }

}

ObjectTable::V ObjectTable::find(ObjectTable::K const & k) {
    auto i = objects_.find(k);
    if( i != objects_.end() )
        return i->second;
    else
        return nullptr;
}

ObjectTable::L ObjectTable::children(ObjectTable::K const & k) {
    auto i = children_.find( basename(k) );
    if( i != children_.end() )
        return i->second;
    else
        return L({});
}

bool ObjectTable::remove(ObjectTable::K const & k) {
    auto i = objects_.find(k);
    if( i != objects_.end() ) {
        objects_.erase(i);
        //guaranteed to exist if object exists
        std:assert( children_.find( basename(k)) != children_.end() );
        auto j = children_.erase( basename(k) );
        return true;
    }
    else {
        return false;
    }
}

int main() {
    auto t = ObjectTable::get();


    t->insert("/realms/silenus", new object());

}`
```

**Comment by thefallentree** [comment]
The  "strong" objection I have is directly use full type everywhere instead of 

```
    using K = std::string;
    using V = object*;
    using L = std::list<V>;
    using M1 = std::unordered_map<K,V>;
    using M2 = std::unordered_map<K,L>;
    using S = std::shared_ptr<ObjectTable>;
```
This is pretty much unnecessary and make rest of the code pretty hard to read without IDE.

another issue to consider is unorderd_map will grow unboundly , it is best to use gametick event to register a clean hook. 

Also, there need to be checks on object_t destruction to remove it from the object table, but triggering this delete is pretty costly, because we will need to search the table ,  So in callout code I end up having to use a "valid" boolean on deletion and check it everywhere else.

**Comment by cartercheng** [comment]
Actually I find the code easier to read with the using type aliases. It is easy to reference the type alias to see what the definition means and it is also easier to update the type for example the original V definition was a std::shared_ptr<object> but I changed it to object* since mixing bare and smart pointers doesn't really work even though C++17 guidelines generally recommend that one doesn't use bare new. 

Well the cost is design to directly emulate the current otable interface. I think when an object_t is destroyed it is responsible for deleting itself from the table.  I don't think there is anyway to control how the stl containers generally handle memory this is one general limitation in using STL inside the driver. 

Searching the table should also be quite cheap since it's a hash table and has O(1) complexity for searching. 

For me the main remaining issue is how to interface the code with google testing framework. The basename function might need to be in it's own class and called (creating a dependency) between the this class and the helper class. This would allow that me to write some test code for the basename function.

**Comment by cartercheng** [comment]
I find looking over the current otable.cc that this needs some sort of statistics reporting that is meaningful which replaces the old reporting. I am not sure what is meaningful to say about the memory usage of the STL container though.

**Comment by quixadhal** [comment]
I don’t know who will care about that level of reporting in a hobby code project today, but if you did… I would want to see something like this, all values totally made up just to look cool:

Object#1234 “sword#3” (object) (15200 bytes)
    .name (string) (47 bytes)
    .hitpoints (mapping) (31 bytes)
        .current (integer) (8 bytes)
        .max (integer) (8 bytes)

And so on… the idea being, if you’re looking at a base type field (integer, string, float), you see the memory used by that item.  If there’s STL overhead beyond the value itself, that could be included… so in my made up example, the “name” property is a string that’s 46 bytes long with the NUL terminator.  If std::string has overhead for being a string, the number shown might be higher.

My thoughts on this are that in the LPC layer, you want to know how many objects of a given type you can create or copy, for example if you were using an overland terrain map, you might want to know how big a rectangle of the map data you can load at once.  As such, it doesn’t matter how much detail you see, but the numbers need to count everything, even overhead that you can’t get at from the LPC layer (such as the STL container overhead).

If you’re looking at the numbers from the driver side (debugging), you would want to see a breakdown.  Maybe you might even care how much is STL container vs. how much is actual data.  But, this kind of depth is likely only EVER going to be used by someone working on the driver itself, which is a very tiny percentage of the folks who use the driver.

I would probably make tracking such statistics a compile-time option, unless you expect other code to rely on it anyways.  Very few people would inspect the results, and it will incur some overhead to update the statistics, which can matter if you’re a large MUD.

Sent from Mail for Windows 10

**Comment by cartercheng** [comment]
The problem is I don't believe it is possible to tell how much memory a STL takes up. It does not report on it in general and thus you cannot compute the overhead on top of the amount of space taken up by the elements in it. I believe unordered_map reports has some other statistics on hash table efficiency that could be reported.

**Comment by thefallentree** [comment]
I spent some time a while ago to convert the driver source code to google style.  and i think there are no reason not to continue follow that style.

as i said, there are no point trying anything c++17, because for 3.0 release we wont raise compiler version requirement.

also, new implementation must still do all what old code does, otherwise it is still not suitable for 3.0.

as for googletestframework, you neee to be more specic what issue you meet and your setup.

**Comment by cartercheng** [comment]
That may be a bit of a problem since the stats reporting is mostly not meaningful without maintaining the old data structure. I suspect the best effort method is to just report what the unordered_map statistics report.

**Comment by cartercheng** [comment]
Also I am curious what you mean by google style. Does google have a style guideline? I have only cursorily examined the v8 source code.

**Comment by thefallentree** [comment]
https://google.github.io/styleguide/cppguide.html

**Comment by cartercheng** [comment]
Thanks for the link but the opinion differs a bit from this one by Herb Sutter-

[](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/)

**Comment by cartercheng** [comment]
I have revised the code a little bit but it is still a bit naive- i.e. if too many elements are deleted space is wasted and the buckets etc are not rehashed. I could still add this to the code-

Here is the current version-

`#include<cassert>
#include<list>
#include<memory>
#include<string>
#include<unordered_map>

#define TESTING
#ifdef TESTING
struct object_t
{
public:
    std::string name;

    object_t(std::string const & s)
    :name(s) {}
};
#endif

class ObjectTable final
{
public:
    using K = std::string;
    using V = object_t*;
    using L = std::list<V>;
    using M1 = std::unordered_map<K,V>;
    using M2 = std::unordered_map<K,L>;
    using S = std::shared_ptr<ObjectTable>;

    static S get();
    bool insert(K k, V v);
    V find(K const & k);
    L children(K const & k);
    bool remove(K const & k);
    int showStatus(outbuffer_t *out, int verbose);

    K basename(K k);
private:
    static S instance_;

    ObjectTable();
    
    M1 objects_;
    M2 children_;

};

#include "base/std.h"
#include "vm/internal/otable.h"
#include "otable.h"
#include <sstream>
#include "vm/internal/base/machine.h"

ObjectTable::S ObjectTable::instance_ = nullptr;

ObjectTable::ObjectTable()
:objects_({}),children_({})
{}

ObjectTable::S ObjectTable::get() {
    if( instance_ == nullptr )
        instance_ = S( new ObjectTable() );
    return instance_;
}

bool ObjectTable::insert(ObjectTable::K k,V v) {
    if( objects_.find(k) == objects_.end() ) {
        objects_.insert( std::make_pair(k,v) );
        children_.insert( std::pair<K, L>( basename(k), {v} ) );
        return true;
    } 
    else {
        return false;
    }

}

ObjectTable::V ObjectTable::find(ObjectTable::K const & k) {
    auto i = objects_.find(k);
    if( i != objects_.end() )
        return i->second;
    else
        return nullptr;
}

ObjectTable::L ObjectTable::children(ObjectTable::K const & k) {
    auto i = children_.find( basename(k) );
    if( i != children_.end() )
        return i->second;
    else
        return L({});
}

bool ObjectTable::remove(ObjectTable::K const & k) {
    auto i = objects_.find(k);
    if( i != objects_.end() ) {
        objects_.erase(i);
        //guaranteed to exist if object exists
        std:assert( children_.find( basename(k)) != children_.end() );
        auto j = children_.erase( basename(k) );
        return true;
    }
    else {
        return false;
    }
}

int ObjectTable::showStatus(outbuffer_t *out, int verbose) {

    std::stringstream ss;
    if (verbose == 1) {
        ss <<  "Object name hash table status:" << std::endl;
        ss <<  "Object name hash table status:" << std:endl;
        ss << "------------------------------" << std::endl;
        ss << "Elements:        " << objects_.size() << std::endl;
        ss << "Memory used:     " << objects_.size() * sizeof(V) << std::endl;
        ss << "Bucket count:    " << objects_.bucket_count() << std::endl;
        ss << "Load factor:     " << objects_.load_factor() << std::endl;

        outbuf_add(out, ss.str().c_str());
      }

    if (!verbose) {
        ss << "Memory used:     " << objects_.size() * sizeof(V) << std::endl;
        outbuf_add(out, ss.str().c_str());
    }
    return objects_size() * sizeof(V);
}

ObjectTable::K ObjectTable::basename(ObjectTable::K k) {
    auto i = k.begin();
    for(; *i == '/' ;++i)
    k.erase(k.begin(),i);
    
    auto j = k.find('#');
    if(j != std::string::npos )
        k.erase( k.begin() + j, k.end() );
    i = k.end() - 1;
    for(;i-1 != k.begin() && *i == 'c' && *(i-1) == '.';i -= 2);
    k.erase(i, k.end() );
    return k;
}

int main() {
    auto t = ObjectTable::get();


    t->insert("/realms/silenus", new object_t("/realms/silenus"));

}`

**Comment by quixadhal** [comment]
This will sound a bit mean, but I’m trying to be helpful here.  This is ONLY a critique of the code style, not how it works.

using K = std::string;

That’s horrible.  It’s only something that makes sense to YOU, and only right now.  If you look at that code, or more likely, some snippet of that code, 10 years from now, you’d have to go paw through lots of code to go find that using statement to know what the heck is going on.

This is the same class of hard-to-maintain code as the overuse of single character variable names.

When you write code, you should assume it’s for other people to read, and that they don’t have years of experience with any particular style, language, or project.  Trying to make everything short was an acceptable tradeoff in the old days of 300 baud modems and 80 column displays, but these days you have smart editors that auto-expand things as you type, and while there will be occasions to shorten things for clarity’s sake, I don’t think any of those cases do that.

For example:  using M1 = std::unordered_map<K,V>;

Obscure and unclear.  I have to paw through several statements to figure out it means: std::unordered_map<std::string, object_t *>

To me, shortening that might make sense if you used it all over the place, but I’d shorten it to something that made the meaning clear, such as: using objMap_t = std::unordered_map<std::string, object_t *>;

At least that way, your declaration tells you that objects_ down below is an object mapping, and you can probably see that strings are the keys by the way it’s used.

I have not looked to see what Google’s coding standard would actually for this case, but the idea of coding standards is to make everyone’s code mesh together properly in a project, and to make it clear for everyone to read.  If the standard said always put opening braces on the next line, instead of cuddling them up to the previous, I may not like it… but if I ignore it, then my code sticks out, and people who are used to being able to match braces by indentation levels will be annoyed that my code seems to be missing opening braces until they look twice.

Ages ago, when I worked on my DikuMUD with a small team, I insisted everyone either code to my examples, or run their code through indent (with the settings I provided) before submitting it.  It was a bit of a pain, but at least it meant the stuff I had to review followed the same general pattern as everything else.  The actual style doesn’t really matter, but everyone needs to agree on one and follow it.  Every company I’ve worked for expects this, because otherwise things get very messy and everything takes longer than it should.

Sent from Mail for Windows 10

**Comment by cartercheng** [comment]
Quix. Thanks for the feedback. I actually kind of did that deliberately to see how far one could push the level of abstraction when it came to typing. There are some limitations however given how the code is written which makes me wonder if it is more than a naming issue. I suspect I could call K Key and V Value- but because of the way basename is written a string is assumed for the post part because of the dependency on char and npos. 

The nice thing however about using aliases is the Value is more or less independent (Key isn't quite) of everything so one can plug in arbitrary types by redefining V.

**Comment by cartercheng** [comment]
Pull request submitted.
