### ISSUE TITLE
RC for "no clean_up" and "no reset" 

### ISSUE THREAD

**Issue by zero9k** [fluffos/fluffos#396]
1. Is it possible make the following options in runtime config?
1.1. No add_action
1.2. No clean_up
1.3. No reset

2. Is it possible to make Fluffos support utf8?

**Comment by cartercheng** [comment]
I think fallentree is doing much of the conversion of old statics into runtime features. I am not familiar with his code.

**Comment by virosh** [comment]
The "NO_ADD_ACTION" define is currently not a runtime configuration.
You can configure "no resets" and "time_to_clean_up" from the Mudlib config.
As long as i remember FluffOS supports UTF-8.

**Comment by zero9k** [comment]
All three options can not be configured in runtime config right now. I mean NO reset NO clean up NO add_action AT ALL. Or the driver can let us define the three to 0 which means not do it at all. That’s ok, too.
I forgot a very important option: no_init. Is it possible to define these 4 options in runtime config?

**Comment by zero9k** [comment]
Fluffos fully support utf8 encodings? Really? I mean Chinese characters:p.

**Comment by thefallentree** [comment]
For 1.1, 1.2 and 1.3 , currently you would have to modify local_options and recompile driver. It's possible to do what you ask and it's on the roadmap, however it may have to wait for 3.1 since there are more important stuff to do first.

for UTF-8, the driver currently support iconv , by adding ```#define USE_ICONV``` you can enable related efun and make driver treat network input as UTF8 by default.  read iconv.cc if needed.

**Comment by zero9k** [comment]
@thefallentree @quixadhal thanks a lot. I will learn the USE_ICONV part. And how about making NO_INIT option to be configured in runtime config ? :)

**Comment by Shea690901** [comment]
Another problem with utf8 is `strlen()`:
In many mudlibs it is used to determine the width of some output (for output formatting). Sadly it doesn´t return the output width for a monospaced font but the storage size.
That´s not a problem as long as the encoded symbol needs only a single byte (**most but not all western charachters**) but for every other character set (cyrillic, hebrew, greek, chinese, ...) the storage size is more often than not 4 bytes per symbol.
To be completely utf8 compatible therefor we would need a new efun that can interpret the string and measure it´s output width in a monospaced font...

**Comment by quixadhal** [comment]
The function wcslen() does the job of strlen(), but is wide-character aware.  One could probably make this a runtime option where the strlen() efun could choose to use the C strlen() function (which accurately reports the byte-count), or the C wcslen() function (which accurately reports the number of charactrers).

Fonts should NEVER be a part of the driver, because that’s entirely a client side issue.

Sent from Mail for Windows 10

**Comment by dwwodan** [comment]
yes, that's why we have strwidth() as well, or at least did in 2.27, I 
assume it's still there

**Comment by Shea690901** [comment]
While `wcslen()` count´s the **codepoints** stored inside a wchar string (**not** utf8 but perhaps utf16 or utf32!!!) it doesn´t tell the output width of this string using a monotype font!!!
That´s the same mistake I made recently...
The problem is: there are not only codepoints with a width of 1 but also 0 (beside control characters!) or 2.
Many (all?) symbols for chinese/japanese/... have a width of 2 and, to grant a more uniform type face, there are even codepoints for standard latin symbols with a width of 2!
As such to grant full utf8 compliance, while still being able to use (code from lima - simule_efun/strings):
``` C
string ljust( string s, int width )
{
  int n;

  n = width - strlen(s);
  if( n <= 0 )
    return s;

  return s + power_str(" ",n);
}
```
One would need an efun wich gives the actual output width using a monospaced font...

**Comment by quixadhal** [comment]
The thing is… you can’t do presentation layer details at the data layer.  What if the font *I* happen to use renders ALL characters to one screen position?  Now your second-guessing that some glyphs are 2 wide because that’s what *YOUR* font does, and the padding will be wrong on *MY* display.

For example:  空 (sora) is one glyph.  In my web browser, using a monospaced font, this renders as one character position, just like S does.  In the Putty TELNET client, it renders as 2 character positions.  If you try to hard-code font behavior on the server, one of them will always be wrong.

The nearest thing to correct behavior is to report the number of characters instead of the number of bytes.  武藤彩未 is always 4 characters,  how it displays on your particular device is dependent on your font choice and the rendering system’s interpretation of it.  That kind of decision making is best left in the LPC layer, where it can be easily customized for particular purposes.

For example, if you know the connection is using putty, you know that will take 8 screen positions.  But if I’m using a web based client, maybe it’ll be 4, maybe 8, who knows?

As far as zero-width symbols… I think we all know you have to strip out all non-printable characters before you try to figure out display width.  That’s why we have functions to strip out pinkfish codes (translate them all to the empty string), since the display width of “%^RED%^武藤彩未%^RESET%^” is still going to be either 4 or 8, not 20 or 24, nor the width of it as translated with the ESC[CSI sequences in place.

Sent from Mail for Windows 10

**Comment by Shea690901** [comment]
Cocerning 0-width symbols:
e.g. neither U+0301 nor U+0307 is a control character (they are diacritical marks), still they have a width of 0:
é: is either
U+0065 (LATIN SMALL LETTER E) followed by U+0301 (COMBINING ACUTE ACCENT) [2 characters with a combined width of 1] or
U+00E9 (LATIN SMALL LETTER E WITH ACUTE). [1 charcter with a widrh of 1]

Cocerning 2-width symbols:
You might want to take a look at thos [wikipeddia artivle](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)...

**Comment by thefallentree** [comment]
@zero9k  I can tentatively commit doing 1.2+1.3 in v3.1 in early 2018.

**Comment by quixadhal** [comment]
This further makes my point for me.  They may be “zero width” in some abstract spec, but in reality they will take up space on your screen.  How MUCH space is 100% dependent on the font chosen *AND* the software being used to render it.  Neither of which the MUD server knows anything about.

In magical ideal-land, I’m sure somebody wanted U+0301 to be rendered atop an existing character, the way one used to do with a typewriter by backing the platen up and hitting another key.  Not impossible to do in software, and I wouldn’t be surprised if a few word processors or typesetter packages did it right.  However, I can’t imagine terminal software rendering overlapping characters under any circumstances… most of them have enough trouble trying to get italics right.

So, at the MUD server level, where your LPC code lives, when you’re trying to figure out the presentation width of a string, you have a few choices to make.  You can try to second-guess what the user will see and assume the spec is always right, in which case you omit U+0301 and friends entirely, trap instances where it’s preceding the magic characters it should “combine” with, and deal with the 2 width characters as 2 spaces.  If you do that, you can rest on your high horse and know YOU did everything right, but things will still look wrong to some users, sometimes.

You can make the blanket assumption that if it shows up as printable via is_print() that it’ll be either 1 or 2 width.  In that case, you’re likely to be fairly close, but some users are still going to see it wrong depending on how their own software and font choices deal with it.

You can assume a character is 1 space on the screen, no matter how many bytes it is.  For terminal software that tries to do varying width symbols, you’ll be wrong.  You’ll also be wrong on terminal software that makes all wide-characters take 2 spaces.  But it’ll work right for some.

Finally, the only way to do it 100% accurate… you can force every single player to enter their software used, font used, and settings, so you can keep a giant cross-reference table of exactly how wide every single glyph is for THAT individual player, and do all the overhead needed to render things to the individual, on the fly.  Have fun with that. 😊

Sent from Mail for Windows 10

**Comment by Shea690901** [comment]
There are two possibilities:
1. The terminal program used by the player renders everything according the standard.
 Meaning U+0065, U+0301 (not the other way round!!!) is renderd as é, depending on the font and renderer not neccesarily the same glyph as U+00E9, but at least the same width and as a look alike, also for a window which may display 80 ascii printables per line there is room for 40 full width unicode symbols per line. (I´ll never understand why according to standard the old ascii is half width...)
1. The terminal program used by the players uses a buggy renderer and/or the configured font contains failures...
 Well in this case everything is open and it would even be possible that U+0065, U+0301 where renderd as 空...
 But I think **that** would be something noticed very soon, since it wouldn´t be restricted to the driver output but interfer with everything done from within the terminal. And I for one would rather fast switch to another terminal program and or font and while at my location the usage of full width symbols isn´t that often and corresponding bugs with the rendering of such symbols here would be quiet easily missed, I would think that those players who use those symbols within their daily work with a computer would find such bugs **very** fast...

So it would be relative simple to include full utf-8 support:
- One just has to look at each encoded codepoint within the string
- lookup it´s width in a table
- add all up 
- return the end result...

In my opinion the question is more along the line of including this in the core drvier or as some module (perhaps with overwriting some core efuns), the latter would also make it simple to have several different modules for different encodings (utf-8, utf-16, big5, ebcdic, ...), which is also the reason why I would prefer the module over the core support ;)

**Comment by thefallentree** [comment]
no_add_action is not possible to turn off in runtime, but other two are in for a long time.
