### ISSUE TITLE
change compile -std=c++11 to -std=c++14.

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#397]
I am actually not sure how to do this since the Makefiles have changed a lot since fluffos-2.xx. Where do I set this flag and replace the old flag. I think we might as well since c++14 is already approaching 4 years old.

**Comment by cartercheng** [comment]
Actually Ubuntu 16.04 which is quite old now ships with gcc5.3 and support for c++14 for clang dates back to 2013.....

**Comment by quixadhal** [comment]
Just to chime in here, I run Debian stable, which is ALWAYS years behind on everything because they won’t update things without testing them for stability first.

Gcc –version
gcc (Debian 6.3.0-18) 6.3.0 20170516

clang –version
clang version 3.8.1-24 (tags/RELEASE_381/final)

Note that this system started out as Debian “wheezy”, which was stable back in 2012, and was migrated to “Jessie” when that became stable, and now is “stretch” as it became stable a few months ago.

I guess the question would be… how many people that actually use the driver as c++11 would NOT be able to process c++14 code?  My gut instinct says if you’ve migrated from C to C++ at all, you probably have new enough tools, even if you don’t use the features in your own code.  But I’m curious what others think.

Sent from Mail for Windows 10

**Comment by thefallentree** [comment]
For a fact, centos 6 is still stuck with gcc-4.X . 

I think we can shoot for a c++14 upgrade for 3.1.  which I want to do in early 2018.

**Comment by thefallentree** [comment]
Closing this bug since there are no pressing need for c++14
