### ISSUE TITLE
Issue concerning conversions to STL

### ISSUE THREAD

**Issue by cartercheng** [fluffos/fluffos#412]
I have been thinking about converting more portions of the driver to STL in order to make coding simpler since much of the algorithmic details can be buried in the STL library rather than done like it use to be in custom code before the advent of OOAD. There are certain issues with memory management that I am however not sure about if for example mapping_t is directly replaced with std::unordered_map. I am not sure if this is an issue but one cannot really ever control how much memory the STL container takes up unless one wraps it in another object to perhaps check how many elements it has and so on. Is this a problem?

For most of the rest of svalue_t (LPC datatype) hierarchy the same problem exists. Currently only computational exhaustion is addressed in FluffOS but not memory exhaustion. Should both be handled somehow?

**Comment by quixadhal** [comment]
Just as a fun idea to toss your way…

Because MudOS was written in the early 90’s, back when having 8MB of RAM was a luxury, like most MUDs, it was optimized to use as little RAM as possible.  Thus, the use of a union for LPC variables.  Now, there’s nothing wrong with that, of course.  But if you were to replace the union with a class, you could get an interesting little “trick” to work that wouldn’t otherwise.

From the LPC layer, variables act as if they were really all mixed type.  The “strict type” checking really only issues a warning if you forget to use a typecast, and LPC type casting is backwards from most other languages anyways.  By that, I mean int x = (int) 3.2; doesn’t result in x being 3, but instead just pushes 3.2 into x.  Effectively, you told the compiler” I know it’s the wrong type, but do it anyways”, instead of “Please make this thing into the right type”.

I assume, in the backend, this is saying assign the value 3.2 into the variable’s union float part, since it’s a float, and then also tag the type as float.

If you were to implement variables using a class, you could allow each variable to have a member for the supported LPC types, and have the option to easily do normal type casting, or LPC traditional type “stuffing”.  It’d simply be a matter of the cast operation setting the typeof field and then either pushing the value into the value’s type field… or into the cast’s type field.

Here’s the reason I said class, not struct.  With a class, you can use getters and setters, so whenever any value is assigned, it automatically assigns the appropriately converted value to the other fields.  Why?  Speed and simplicity of type casting.  If I store x = 12; and then later want to do string s = “Hello “ + x; The compiler can just pluck the string value directly, which would already be “12”.  If you later assigned x = “foo”; it would either issue a warning/error, or just assign x to be a string and set the integer part to 0.

Of course, that might be too expensive for some, so it’s also something easily disabled.  The memory cost would need to be eaten though, so it would be smart to try such a change and then load up something very large (Discworld) to see how much real-world memory bloat there is.

The reason I suggest it though is that most MUDs are now run on hardware (or VMs) that has 8GB or more of RAM, processors thousands of times faster, but still performing the same workload.

Sent from Mail for Windows 10

From: cartercheng
Sent: Sunday, January 14, 2018 10:25
To: fluffos/fluffos
Cc: Subscribed
Subject: [fluffos/fluffos] Issue concerning conversions to STL (#412)

I have been thinking about converting more portions of the driver to STL in order to make coding simpler since much of the algorithmic details can be buried in the STL library rather than done like it use to be in custom code before the advent of OOAD. There are certain issues with memory management that I am however not sure about if for example mapping_t is directly replaced with std::unordered_map. I am not sure if this is an issue but one cannot really ever control how much memory the STL container takes up unless one wraps it in another object to perhaps check how many elements it has and so on. Is this a problem?
For most of the rest of svalue_t (LPC datatype) hierarchy the same problem exists. Currently only computational exhaustion is addressed in FluffOS but not memory exhaustion. Should both be handled somehow?

**Comment by cartercheng** [comment]
I am not sure what you are advocating here. I gather you have done some reading on compilers but I am sure no textbook implementation of dynamic typing would do things the way you suggested and I am uncertain what the purpose would be. Storing multiple convertable representations seems a bit odd and I am not sure what is gained by this.
My understanding of the static type system in fluffos is because of call_other kind of broken IIRC unless one goes back to explicitly casting call others like in older versions of mudos.

**Comment by Shea690901** [comment]
I don't see the advantage either....
In most cases I won't need the other types, so the question:
Why store the value in different types if I only need the one?
Should I truly need some conversion it could be done when it is truly needed....

Just because I have much more memory available than back in the days, IMHO it's no reason to splurge on it, especially if it costs (most times) unneccessary CPU time (eventhough we nowadays have much more of this too ;) )...
