### ISSUE TITLE
implement JSON serialize & deserialize efuns

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#429]
https://github.com/ldmud/ldmud/blob/master/src/pkg-json.c

**Comment by thefallentree** [comment]
I don't think LDMUD ever dealt with UTF-8 encoding,  

The only supported encoding for JSON in the open world is UTF-8.  In order to properly implement json serialization & deseralization,  we also need to deal with UTF-8 encoding. through libICU integration. 

So, the plan here is to implement an "broken" version of JSON efuns first,  just ignoring string at first, then when libicu integration is done, strings will be properly translated too.

**Comment by seikichin** [comment]
ldmud is Unicode support
Make LPC strings accept unicode characters by converting all external input into an internal unicode encoding (eg. UTF-8) and make all string routines unicode-aware.

**Comment by quixadhal** [comment]
LPC (and fluffos) has always accepted any character encoding  you like in that it doesn’t mess with them.  However, as you say, functions like strlen() and the ever-buggy sprint() assume single bytes per character.  This has been a problem, historically, ever since the use of color codes (pinkfish sequences) in the mid 90’s.

The typical workaround has been to implement a special color_strlen() sefun to strip out the color codes and return the visible length of a string, which is then used to calculate padding and offsets.  You could do similar for UTF-8 support until the driver has a solution in place.

Sent from Mail for Windows 10

**Comment by thefallentree** [comment]
we now have an LPC json_encode and json_decode in stdlib/ , there is no plan to implement this as EFUN for now.
