### ISSUE TITLE
portbind

### ISSUE THREAD

**Issue by Shea690901** [fluffos/fluffos#575]
Is ```portbind``` still needed  for anything???

**Comment by quixadhal** [comment]
I’ve never used it, but my guess would be that it’s a relic from the days when having root privs on a system was almost never allowed.  Since ports below 1024 are reserved for root only, this lets you beg your sysadmin to setuid portbind to root so it can open the port (usually the TELNET port) as root, then ditch root permissions and exec the real driver with the already opened port dup2’d over. That restriction still applies, but since everyone can run Linux on their toaster oven today, you just be root and setuid-jail if you are worried about security. Sent from Mail for Windows 10 From: Shea690901Sent: Sunday, January 26, 2020 5:51 AMTo: fluffos/fluffosCc: SubscribedSubject: [fluffos/fluffos] portbind (#575) Is portbind still needed for anything???—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by thefallentree** [comment]
@quixadhal  if you can fix your email client and sent plain text replies, everything would works.

@Shea690901 yeah, like @quixadhal explained, portbind is an tcp proxy that suitable for bind to low port numbers, it still has its usage, however I havn't touched it for a long while.
