### ISSUE TITLE
FluffOS has_gmcp(.me) returns 0 when using mudlet with gmcp enabled

### ISSUE THREAD

**Issue by crius-al** [fluffos/fluffos#662]
According to https://github.com/fluffos/fluffos/blob/master/docs/archive/ChangeLog.fluffos-2.x#L109 I can call has_gmcp() on a player object to see if the player object supports gmcp or not. This is failing for .me and I am using mudlet with gmcp enabled.

**Comment by thefallentree** [comment]
1. you need to use `has_gmcp(this_player())` 
2. when using send_gmcp() it use to require calling from player object, this issue has been fixed in https://github.com/fluffos/fluffos/pull/661 

which also contains an GMCP example (tested work fine with mudlet)

![image](https://user-images.githubusercontent.com/1256464/92290805-52e89480-eeca-11ea-9177-530a49fca066.png)

**Comment by thefallentree** [comment]
fixed in #661
