### ISSUE TITLE
Segmentation fault (Address not mapped to object [0x6448])

### ISSUE THREAD

**Issue by yiwang-dev** [fluffos/fluffos#671]
our mud got this error and crashed, we recently upgraded from old version to 2019.
There's no other errors logged in debug.log.

Thanks

**Comment by thefallentree** [comment]
This is usually due to some memory corruption, since the error address is corrupted (not mapped to any object) it is hard to diagnostic,  Can you make sure you run with core dump enabled? so next time it happens it will have an core dump ?

https://www.fluffos.info/bug.html#gsc.tab=0 also contains ways you can build santizied driver / under GDB to help you catch this kind of issue eariler.

**Comment by gesslar** [comment]
I just got this, too.

Stack trace (most recent call last):
#12   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#11   Object "./driver", at 0x55bfb81b706d, in _start
#10   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f4e71c830b2, in __libc_start_main
#9    Object "./driver", at 0x55bfb81b7018, in
#8    Object "./driver", at 0x55bfb82c6307, in
#7    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7f4e70fe687e, in event_base_loop
#6    Object "/lib/x86_64-linux-gnu/libevent-2.1.so.7", at 0x7f4e70fe5fdd, in
#5    Object "./driver", at 0x55bfb82043b9, in
#4    Object "./driver", at 0x55bfb81ff238, in
#3    Object "./driver", at 0x55bfb82801aa, in
#2    Object "./driver", at 0x55bfb827ee12, in
#1    Object "./driver", at 0x55bfb82916ae, in
#0    Object "./driver", at 0x55bfb82799aa, in
Segmentation fault (Address not mapped to object [0xffffffffffffffdc])
Segmentation fault
