### ISSUE TITLE
fluffos v2021 plan

### ISSUE THREAD

**Issue by thefallentree** [fluffos/fluffos#721]
Here are the current plan for both v2019 & v2011:

V2019

1) the last major feature for will be observibility & performance: 
- macro & micro performance benchmark suite with Cpython references  (currently we are looking at about 3x performance difference compare to same python code).
- enhance memory accounting facilities, allow debugging issues with circular references, dangling objects etc, etc.

V2011

will start with language ecosystems improvement, allowing people to write better lpc code faster.   
- introduce ".lpc" as alternate file extension.
- lpcfmt , standlized lpc code formatter, one style for all.  (maybe in Rust)
- (may not be able to fit in) lpcc enhancement for auto completion supports in various IDEs.  

then will move on to integration features:
- generic C API integration efun, make it possible to call any shared library from LPC.
- TLS support for lpc socket efuns

finally, will come to multi core support.
- we will start with multithread networking, likely a clean-up in the process too.
- LPC RMI, call_other on lpc object on another driver over network.

**Comment by lostsnow** [comment]
1. Customize the extension of the LPC file, e.g. `.lpc`
2. High precision data type or libs (decimal/bcmath)
3. Driver-level LPC code reload/update (update all referenced objects)

**Comment by staun** [comment]
Regarding fallentree's list, my vote goes to:
#4 as primary (shift-alt F in Visual Studio Code to format all things in Good ways!), #3 as secondary.

Working with blind programmers #4 becomes really important since they cannot indent their files at all (that's just not happening), and they'd like to be able to leave their code in a good state as well. Lots of blind people in the MUDding community as well, so I see this as a very strong use case to support them.

Lostsnow:
#3 would be my highest vote on your list :-)

**Comment by seikichin** [comment]
Let me say a joke children do multiple choice questions, adults of course want all of them.

**Comment by crius-al** [comment]
I've always wanted multithreaded lpc execution.
This may destroy the mud I work on though. I don't really know.
It pains me how often players are paused because some player somewhere does something processor intensive, like "look" when they are over 100 objects lying around, and we use LPC to calculate the distance to each object and where it is,

This is a thing:
------------------------------------------------------------------
A burning wood campfire is to the northwest.
A wooden stick is to the northwest.
Some smooth rocks are to the northwest.
Lots of tree branches are to the northwest.
Three wooden axes are to the northwest.
A male goblin with wild reddish-black hair ( Zebu ) is standing to the
northwest.
Lots of leather bowstrings are to the northwest.
A hawkshelf fungus is to the northwest.
A partially completed chunk of wood is to the northwest.
A great many chunks of wood are to the northwest.
A wood campfire is to the northwest.
A partially completed leather bowstring is to the northwest.
Yezrah is sitting down to the northwest.
An iron chisel is to the northwest.
A stone hammer is to the northwest.
Some glass bottles are to the northwest.
Some wooden spears are to the northwest.
An extremely large pile of slightly decayed bear meat is to the northwest.
A small tin box is to the northwest.
A stone knife is to the northwest.
A very large pile of badly decayed deer meat is right next to you.
A sheet of leather is right next to you.
A rabbit hide is right next to you.
A wolf hide is right next to you.
A roughspun tunic is right next to you.
Two sprigs of parsley are to the north.
A wooden quarterstaff is right next to you.
A simple hand saw is right next to you.
A wooden handle is right next to you.
Some wood logs are right next to you.
A long wooden handle is right next to you.
A great many unused bandages are right next to you.
Many crude wooden arrows are right next to you.
Some wooden arrow shafts are right next to you.
Three wooden tent poles are right next to you.
==================================================================

Since every single object independently has to determine its position relative to the looker, when players put about 200 or so objects down in a room, the lpc starts saying too long evaluation.

So, to be clear, I'd like to be able to spin up a second thread to handle stuff done in a call_out, call_other, or some other method so we can handle people looking (or doing things that at least don't modify the room).

**Comment by thefallentree** [comment]
@crius-al if the goal is to get around too long evaluation then you can already do it using defer() , call_out(0) and  some other form of  async execution.  In JavaScript you will use chained promise , all of these are easier than dealing with an separate thread . 

The separate thread functionally will be similar to is evaluate over network in another process using Python style pickleing & multiprocessing or Java style RMI, I haven’t decided on which what is the most intuitive one yet.

**Comment by crius-al** [comment]
Thanks for your advice, but getting around too long evaluation is easy. What is difficult is not pausing everyone during a look, and not cutting the player off mid look where they are allowed to do other things.
Ideally, I'd like every character to be running on a separate thread, and able to do what they want by posting events to an event queue - like Windows does. Each player can then do what they want, and while they are busy waiting for info, every other player can run around and do what they want. The player who types look then gets their look done before they can do other stuff.

I have a lot of experience programming multi-threaded applications in Windows using c and c++. I understand that objects could have multiple people interacting with it and cause fun errors.
There are so few players spread around these days that what I really want to stop the mud pausing the world just because someone types look.
Maybe I need to transfer all the room contents to an efun to be processed faster - but then we can't easily change what people see... and it won't be fun dealing with LPC objects in an efun.
I do not understand how I could use call_out to avoid pausing the entire world. All the look processing is still done on 1 thread, and it will still pause the entire world while the look is running. After looking at this defer() you mention, it seems to be an array of functions to be called in FIFO or LIFO order. It still runs on the same thread the world runs on, which means it still pauses the world when it runs.
As an avid player of EVE online, I have watched how EVE Online's single threaded server code (stackless python) removes nearly all the power of their servers since only 1 thread can run at once, and all the players start to run extremely slowly if just 1 person smartbombs a fleet. Single threaded execution of code might have been fine 20 years ago, but even the weakest desktop computers have multiple CPUs these days - not taking advantage of them is such a waste.

Granted, this is close to impossible, but it's a wishlist, not a realitylist. :)

**Comment by staun** [comment]
So exciting! Wonder what Santa brings us for Xmas this year ;)

**Comment by thefallentree** [comment]
If you use call_out(0.1)  to chain all the processing , it will be
identical to what any event bus based single thread server provides: e.g
process.nextTick() in nodejs etc.

If one want to utilize multiple core, that will spread work across cpu core
dimensions, then one will have to pay communication overhead when sending
request & result back and forth.

So, it require two approaches for different purpose.

**Comment by crius-al** [comment]
I would rather use multiple cores to spread the work across cpu cores.
It doesn't matter to me how exactly it's done, but that is my wish list item.

**Comment by crius-al** [comment]
This is an extremely small wish though - players who play text based games probably don't care if it takes them 5-10 seconds for them to see the results of looking around (and it sometimes does for our mud). Having the world pause doesn't seem to be a complaint, but it's something I have personally noticed when trying to do things on our empty test mud with no players around, in an empty room. Our daemon processes that run the world sometimes take up too much CPU, and all they do is make sure everything in the world decays a bit, and destroys items that reach a decay threshold... or clean up memory, or unload rooms based on no one being there for a long time, or... or... so many tasks that deal with trying to stop the mud from using up too many resources, but try to trade current CPU power for future saving of memory and CPU....

**Comment by staun** [comment]
I'm intrigued by your problem, @crius-al , I've never seen that issue with mudlibs I worked on. I wonder how this 'look' with many items impacts you so much. I have a feeling that you can redesign your way out of it.

**Comment by crius-al** [comment]
Pasted below is our object view code alone. Although there is more code called that does additional processing, this is where I believe the processing of the object code is.

This code is run every time someone looks.

`//////////////////////////////////////////////////////////////////////
//:FUNCTION make_objects_string
//////////////////////////////////////////////////////////////////////
//string make_objects_string(object array obs, string prefix)
//
// Return a string describing the objects given in "obs". The string
// "prefix" is placed in front of the object description.
string make_objects_string(object array obs, string prefix) {
   string output,str,count_str,begining,end;
   array arr;
   int size,count;

   output="";
   arr=obs->in_room_desc(you());
   arr=map(arr,(: ADJECTIVE_D->parse_adjectives($1,you()) :));
   size=sizeof(arr);
   for (int i=0;i<size;i++) {
      if (!duplicatep(arr,i)) {
         count=count(arr,arr[i]);
         if (count>1) {
            str=obs[i]->plural_in_room_desc(you(), count);
            if (strlen(str)) {
               switch(count) {
                  case 2:      count_str="two ";break;
                  case 3:      count_str="three ";break;
                  case 4..8:   count_str="some ";break;
                  case 9..20:  count_str="lots of ";break;
                  case 21..50: count_str="many ";break;
                  default:     count_str="a great many ";break;
               }
               if (sscanf(str, "%s" + obs[i]->plural_short() + "%s",
                          begining, end) == 2)
                  str = begining + count_str + obs[i]->plural_short() + end;
               str = ADJECTIVE_D->parse_adjectives(str, you());
            }
         }
         else
            str=arr[i];
         if (obs[i]->is_hiding()) {
            if (str[<1]=='.')
               str [<1]=' ';
            str+="(trying to hide).";
         }
         if (strlen(str)) {
            if (str[<1]!='.')
               str+=".";
            output+=cap(str)+"\n";
            if (obs[i]->test_flag( INVIS ))
               output="(Invisible) "+output;             
         }
      }
   }

   str="";
   if (strlen(output) || you()->get_furniture_used()) {
      if (!(show_objects_only()) && you()->get_message_flag(LINES_FLAG))
         str+=
      "------------------------------------------------------------------\n";
      str+=prefix;
      str+=this_user()->get_items_color();
      str+=output;
      str+="%^RESET%^";
      if (this() == environment(you()))
         if (you()->get_furniture_used())
            str+="%^CYAN%^On {an}"+you()->get_furniture_used()->short()+
            ":  %^RESET%^"+you()->get_furniture_used()->show_occupants()+"\n";
      if (!(show_objects_only()) && you()->get_message_flag(LINES_FLAG))
         str+=
      "==================================================================\n";
   }
   return str;
}

//////////////////////////////////////////////////////////////////////
//:FUNCTION show_objects
//////////////////////////////////////////////////////////////////////
//varargs string show_objects(mixed except);
//
// Return a string describing the objects in the room
// except can be an object or an array of objects, these object(s) are
// excluded from the result.
//////////////////////////////////////////////////////////////////////
varargs string show_objects(mixed except) {
   object *obs, *obstacles;
//   string result;      //specifically for hiding
   int light,mysize;

   obs = filter(all_inventory() - ({ this_body() }),
           (: $1->is_visible() :));

   if (arrayp(except))
      obs -= except;
   else if (objectp(except))
      obs -= ({except});

   if (!sizeof(obs))
      return "";

   // This code removes some objects from the list of what can
   // be seen, due to light restrictions.  It should probably
   // only be applied to glances.  -- Lathander
   if (show_objects_only()) {
      light=you()->get_perceived_light(this());
      if (light!=100) {
         mysize=sqrt(to_float(you()->get_stat(WEIGHT)/1000))*1000;
         switch (light) {
            case 0:
               obs = filter(obs, (:gives_light:));
               break;
            case 1..99:
               obs = filter(obs, (:can_see_obj:),100-light,mysize );
               break;
            case 101..199:
               obs = filter(obs, (:can_see_obj:),light-100,mysize );
               break;
            case 200:
               obs = ({});
         }
      }
   }

   //The following was added so that a player does not see in the
   //list of items in the room the furniture they are using nor
   //the things on it.  These are presented later.
   if (you()->get_furniture_used()) {
      obs -= ({you()->get_furniture_used()});
      obs = filter(obs, (: $1->get_furniture_used() !=
         you()->get_furniture_used() :) );
   }

   // check line of sight if there are obstacles in the room
   obstacles = filter(all_inventory(this()),
                      (: $1->is_obstacle() && $1->is_opaque() :)
      );

   if (sizeof(obstacles)) {
      array eye_coord = you()->has_coords();
      eye_coord[2] += to_float(you()->get_stat(HGT)) / 100;
      obs = filter(obs, (: filter_blocks, obstacles,  eye_coord :));
   }

   return make_objects_string(obs,"");
}`

**Comment by crius-al** [comment]
My wish for fluffos is to be able to spin up a thread to run look for a player. It would make sense to be able to do this for any command that doesn't change anything. Look is purely informative, so this passes such a requirement. I would love if all the computations needed for look were done for that player in a thread separate from other players on the mud.

If I had a special efun where I could pass it a LPC function name to run in a separate thread (and probably this_player() too, since we need to know who is looking) that would be ideal, and probably not too difficult.

**Comment by thefallentree** [comment]
@crius-al Whenever you execute stuff in a separate execution context you will run into data sharing issues. I am not convinced it is wise to introduce threading and data sharing in LPC , just like python doesn't really have threading, however they do have I/O cancellation points. 

So, in the current plan I will focus on process pool instead,  you will likely not able to run "look" in that pool (doing so will require a lot of data sharing and it is unlikely to be worth it , but running things like grep should be very much feasible and beneficial).

**Comment by thefallentree** [comment]
Here are the current plan for both v2019 & v2011:

V2019

1) the last major feature for will be observibility & performance: 
- macro & micro performance benchmark suite with Cpython references  (currently we are looking at about 3x performance difference compare to same python code).
- enhance memory accounting facilities, allow debugging issues with circular references, dangling objects etc, etc.

V2011

will start with language ecosystems improvement, allowing people to write better lpc code faster.   
- introduce ".lpc" as alternate file extension.
- lpcfmt , standlized lpc code formatter, one style for all.  (maybe in Rust)
- (may not be able to fit in) lpcc enhancement for auto completion supports in various IDEs.  

then will move on to integration features:
- generic C API integration efun, make it possible to call any shared library from LPC.
- TLS support for lpc socket efuns

finally, will come to multi core support.
- we will start with multithread networking, likely a clean-up in the process too.
- LPC RMI, call_other on lpc object on another driver over network.

**Comment by staun** [comment]
Psst... I think you mean "v2021" ;-)

**Comment by thefallentree** [comment]
you are right ;-D, corrected
